🔀 :: 이메일 인증로직 호출
GSM-MSG/GCMS-Android pull request #62
Opened 2022-03-28 14:32 UTC by khs3994

이메일 인증로직 호출 부분을 구현합니다

2022-03-29 02:51 UTC, chanwoo00106 approved these changes
맛있다

2022-03-29 02:56 UTC, sihun96 approved these changes

2022-03-29 06:41 UTC, baekteun requested changes
failure 케이스 만드셈 ㅅㄱ

2022-03-29 06:42 UTC, kimsh153 approved these changes

2022-03-29 06:45 UTC, khs3994 commented
> failure 케이스 만드셈 ㅅㄱ

인증 실패했을때 경우 만들라는거?

2022-03-29 06:46 UTC, baekteun commented
> > failure 케이스 만드셈 ㅅㄱ
> 
> 인증 실패했을때 경우 만들라는거?

ㅇㅇ

2022-03-29 10:29 UTC, sagwamatrlawns approved these changes

2022-03-30 06:23 UTC, louis7308 approved these changes
맛있다

2022-03-30 14:44 UTC, leehyeonbin approved these changes

2022-03-30 14:45 UTC, baekteun approved these changes

2022-03-30 23:41 UTC, merged